const ENCRYPTED_FILE_EXTENSION_CENC = 'cenc';

export const ENCRYPTED_FILE_EXTENSION_DEFAULT = ENCRYPTED_FILE_EXTENSION_CENC;


export const ENCRYPTED_FILE_EXTENSIONS = [
	ENCRYPTED_FILE_EXTENSION_CENC
];
